### ISSUE TITLE
Cannot enable repo

### ISSUE THREAD

**Issue by fiorinoh** [morxa/fedora-rcll-refbox#1]
Hi, dnf copr enable thofmann/rcll-refbox ends up with an error message on f25:
'Error: This repository does not have any builds yet so you cannot enable it now.'
Also seems to have several failed builds.

**Comment by morxa** [comment]
Fedora 25 has been EOL since 2017, please upgrade to Fedora 32 or Fedora 33.

COPR automatically disables the repo for EOL releases.

**Comment by morxa** [comment]
If you still have issues with the installation, feel free to re-open this issue!
